- README.md
- aries_staticagent/__init__.py
- examples/cron.py
- examples/cron_returnroute.py
- examples/webserver_aiohttp.py
- requirements.dev.txt
- requirements.txt
- setup.py
Once we have a package published, we will need to reword the readme.
> Fixing up for publishing

- README.md
- aries_staticagent/__init__.py
- aries_staticagent/dispatcher.py
- aries_staticagent/message.py
- aries_staticagent/module.py
- examples/cron.py
- examples/webserver_aiohttp.py
- keygen.py
- setup.py
- tests/test_dispatcher.py
- tests/test_module.py
- Make Keygen a convenience method and call from script
- Correct dependency installation instructions
- Improved Module interface
- Rename "Agent" to "Dispatcher"
- Other restructuring
- Bump minor version
> Release 0.2.0

- aries_staticagent/crypto.py
- aries_staticagent/mtc.py
- aries_staticagent/static_connection.py
- aries_staticagent/type.py
- tests/test_crypto.py
- tests/test_dispatcher.py
- tests/test_message.py
- tests/test_module.py
- tests/test_mtc.py
- tests/test_pack_unpack.py
- tests/test_routing.py
- tests/test_type.py
- tests/test_utils.py
Added tests for more complete code coverage. The least code coverage now lies within `crypto.py`. I intend to rework that file while switching out the sodium library. Another PR for that to follow.
> Improve Code Coverage

- RELEASES.md
- setup.py
> Prepare version 0.5.0 release

- aries_staticagent/static_connection.py
> Fix condition and timeout setting on send_and_await_reply

- aries_staticagent/message.py
> Add __eq__ to message

- .github/workflows/test_on_pr.yml
> Create Github Action for Testing PRs

- .github/workflows/test_on_pr.yml
- aries_staticagent/dispatcher.py
- aries_staticagent/static_connection.py
- tests/test_pack_unpack.py
- tests/test_static_connection.py
> Fix linting and tests

- aries_staticagent/crypto.py
To verify not only that the message is signed but that the signer is
who we expected.
> Return message field signer

- RELEASES.md
- setup.py
> Prepare v0.5.1 release

- README.md
- aries_staticagent/crypto.py
- aries_staticagent/static_connection.py
- aries_staticagent/utils.py
- examples/cron.py
- examples/return_route_client.py
- examples/return_route_server.py
- examples/webserver_aiohttp.py
- examples/webserver_with_module.py
- tests/test_pack_unpack.py
- tests/test_routing.py
- tests/test_static_connection.py
This will help ensure that updating some values of connection info does
not result in other values not being properly updated.
> Add support for routing, multiple recipients

- aries_staticagent/static_connection.py
Signed-off-by: artem.ivanov <artem.ivanov@dsr-company.com>
> Fixed preparation of `Forward` message

- RELEASES.md
- setup.py
> Prepare 0.6.1 release

- aries_staticagent/static_connection.py
> Fix encoding of sent plaintext messages

- aries_staticagent/__init__.py
- aries_staticagent/static_connection.py
Rename to MessageDeliveryError
> Add message delivery status to error

- .github/workflows/test_on_pr.yml
- requirements.dev.txt
> Add coverage to github action

- .github/workflows/publish_release.yml
> Add publish release workflow

- aries_staticagent/static_connection.py
> Allow extra keyword arguments in update

- RELEASES.md
- setup.py
> Prepare 0.7.0 release

- aries_staticagent/crypto.py
- tests/test_crypto.py
> Accept base64URL values with or without padding

- RELEASES.md
- setup.py
> Prepare release 0.7.1

- aries_staticagent/crypto.py
- aries_staticagent/static_connection.py
- examples/common.py
- examples/cron.py
- examples/return_route_client.py
- examples/return_route_server.py
- examples/webserver_aiohttp.py
- examples/webserver_with_module.py
- tests/test_examples.py
Separate common code into new file, improving clarity of the examples. Add new tests to ensure examples are working.
> Minor refinements in examples

- aries_staticagent/utils.py
- examples/preprocessors.py
- tests/test_examples.py
- tests/test_utils.py
> Add preprocessing decorators for message handlers

- aries_staticagent/static_connection.py
- aries_staticagent/type.py
- examples/return_route_client.py
> fix: timeouts for send and await reply not applied to send

- pyproject.toml
> chore: bump version for pre-release

- examples/return_route_client.py
> fix: await returned in return route client

- aries_staticagent/__init__.py
- aries_staticagent/module.py
- examples/webserver_with_module.py
- tests/test_module.py
- tests/test_routing.py
BREAKING CHANGE: route method is replaced with ModuleRouter
> refactor: simplify module routing

- aries_staticagent/connection.py
- aries_staticagent/message.py
- examples/cron.py
- tests/test_send.py
> fix: allow return route to be set by msg in send

- aries_staticagent/message.py
- tests/test_message.py
> fix: allow str or MsgType in base message defs

- aries_staticagent/module.py
- tests/test_module.py
> fix: modules can use protocol identifier for protocol

- aries_staticagent/dispatcher/queue_dispatcher.py
- tests/test_msg_queue.py
> fix: busy loop under certain conditions in msg queue

- tests/test_msg_queue.py
> test: msg not initially present on queue
